CREATE TABLE FORMULA(
FORMULA_ID INT  AUTO_INCREMENT PRIMARY KEY,
FORMULA_NAME VARCHAR(100),
USER_ID INT,
PROPERTY_TYPE VARCHAR(100),
AREA_ID INT,
BORROWER_TYPE VARCHAR(100),
NOTE_TYPE VARCHAR(100),
VALUE_ADJUSTMENT VARCHAR(100),
RISK_ADJUSTMENT VARCHAR(100),
 UPDATED_DATE_TIME DATE NULL,
  UPDATED_BY  VARCHAR(45) NULL,
  CREATED_DATE_TIME DATE NULL,
  CREATED_BY  VARCHAR(45) NULL);