

CREATE TABLE NOTE_ADDRESS (
NOTE_ADDRESS_ID INT AUTO_INCREMENT PRIMARY KEY,
NOTE_ID INT,
STREET_ADDRESS  VARCHAR(300),
CITY VARCHAR(100),
STATE VARCHAR(100),
COUNTRY VARCHAR(100),
ZIPCODE VARCHAR(20),
AREA_ID INT,
 UPDATED_DATE_TIME DATE NULL,
  UPDATED_BY  VARCHAR(45) NULL,
  CREATED_DATE_TIME DATE NULL,
  CREATED_BY  VARCHAR(45) NULL)